### ISSUE TITLE
Error occured while I use :Lf .

### ISSUE THREAD

**Issue by fgheng** [ZhiyuanLck/vim-lf#1]
* Make sure to search for a solution in old issues before posting a new one.
* Learn at least a minimum of Markdown formatting (https://guides.github.com/features/mastering-markdown).

**Information**
- platform and distribution (windows 10, ubuntu 18.04, ...)
- arch
- terminal (gnome terminal, xterm, alacritty, ...)
- tilix
- vim version (for example: vim 8.2 included patch 2017 or the output of `vim --version`)
- NVIM v0.5.0-dev+950-g5ce328df4
- error message (output of `:messages`)
- 
![image](https://user-images.githubusercontent.com/50551377/102709033-c11e5f00-42e1-11eb-90af-93fb25b0d2a4.png)

**Describe the bug**
A clear and concise description of what the bug is. Maybe need some screenshots.

**To Reproduce**
First you need a minimal setting file: `minimal.vim`
```vim
set nocompatible
" change to your own path
let &runtimepath  = '~/.vim/bundles/vim-float-terminal,' . &runtimepath
```
Then run vim via `vim -u minimal.vim somefile`.
Steps to reproduce the behavior in vim:
1. In normal mode, press ...
2. run ex commands ...
3. ...

**Additional context**

**Comment by ZhiyuanLck** [comment]
nvim is not supported yet
